### ISSUE TITLE
Building milter-spamc?

### ISSUE THREAD

**Issue by purplealert** [SirWumpus/milter-spamc#1]
I have managed to build the updated libsnert using the new instructions and I'd like to build the milter-spamc against that but unfortunately I haven't been able to work out how to get it working.  I have used it from before, so I'd like to be able to use it on a more modern system as well, I'm building against alma linux 8.

Having grabbed the source and added it to the com/snert/src folder, I ran automake to create something buildable.  Configure appears to work but then it throws the following error when running 'make build'

`gcc -DMILTER_BUILD=`cat /usr/local/src/com/snert/src/milter-spamc/BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat /usr/local/src/com/snert/src/milter-spamc/BUILD_ID.TXT`'"' \
  -I/usr/include/libdb   -Wall -Wno-unused -Wno-char-subscripts -m64 -I./../../include    -L/usr/lib64   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-spamc milter-spamc.c -lsnert  -lpthread -lmilter -lm -ldb -lpthread -lpthread
milter-spamc.c:1261:14: error: expected expression before ‘,’ token
  MILTER_MAJOR,
              ^
`

Any suggestions would be gratefully received.

Thank you.

**Comment by SirWumpus** [comment]
* `automake` is not supported.  Only `autoconf` is needed to rebuild the `./configure`, though there should be a current one supplied with `libsnert` and `milter-spamc` repos.  Each `./configure` script will generate the makefiles.

*  Build `libsnert` first as described, see [SirWumpus/libsnert](https://github.com/SirWumpus/libsnert?tab=readme-ov-file#configuration--build), eg.
```
cd com/snert/src/lib
make distclean                 # only if you've previously configured and built libsnert
./configure [options]
make
```
then switch to the milter, eg.
```
cd ../milter-spamc
./configure
make
sudo make install
```
That should be it.

**Comment by purplealert** [comment]
Many thanks for getting back to me, yes that's what I was trying to do based on the previous versions.  We've used this milter with great success in the past(bought a licence many years ago) and was hoping to use it again.

My issue is that once I've git cloned the milter-spamc repo into the appropriate location,  I still don't have enough to run `./configure`

I can run `autoconf`, which generates some of what's required and it now passes the configure stage, but it still won't make successfully.

`make: *** [makefile:126: milter-spamc] Error 1`

I'm sure I'm missing something obvious here, but I'm afraid I don't know enough about the process to get much further.  It appears that possibly some files are still missing from the repo?  The BUILD_ID.TXT file seems to play some part in this and it just seems to contain 0, it's also complaining about a missing token, MILTER_MAJOR?

I appreciate your assistance.

**Comment by SirWumpus** [comment]
* Forgot to include a pre-made `configure` script.
* Fixed compiler warnings.
* Tweak version/build handling.
